#!/bin/sh

# Move Tor process to dedicated CPUs and strongly discourage interruption
pgrep -u _tor tor | while read pid; do
	cpuset -p $pid -s 2 -l 2,3
	renice -15 -p $pid 2> /dev/null
done

# Move everything else off of dedicated CPUs
cpuset -s 1 -l 0,1

