#!/usr/bin/env sh
set -e
cd -P "$(dirname -- "$0")/.."

main() {
  connect
  
  apply_overlay
  restart sysctl
  restart ipfw
  reload tor

  disconnect
}

DEPLOY_TARGET="the-windy-onion.tor-exits.alec.ninja"
CONTROL_SOCKET="$(mktemp -d)/control.sock"

apply_overlay() {
  echo "\n--- APPLY OVERLAY"

  scp_with_socket -r overlay/* "$DEPLOY_TARGET:/"
}

restart() {
  echo "\n--- RESTART SERVICE $1"

  ssh_with_socket "$DEPLOY_TARGET" -- sudo service "$1" restart
}

reload() {
  echo "\n--- RELOAD SERVICE $1"

  ssh_with_socket "$DEPLOY_TARGET" -- sudo service "$1" reload
}

connect() {
  echo "--- CONNECT $DEPLOY_TARGET"

  ssh \
    -oControlMaster="yes" \
    -oControlPath="$CONTROL_SOCKET" \
    -oStrictHostKeyChecking="yes" \
    -oUserKnownHostsFile="keys/known_hosts" \
    -oUser="root" \
    -i "keys/deploy.key" \
    "-qfN" \
    "$DEPLOY_TARGET"
}

disconnect() {
  echo "\n--- DISCONNECT"

  ssh_with_socket -qO exit "$DEPLOY_TARGET"
}

ssh_with_socket() {
  ssh -oControlMaster="no" -oControlPath="$CONTROL_SOCKET" "$@"
}

scp_with_socket() {
  scp -oControlMaster="no" -oControlPath="$CONTROL_SOCKET" "$@"
}

main "$@"
exit 0